version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pnpm"
    directory: "/firebase/functions/"
    schedule:
      interval: "weekly"
