name: Deploy to Firebase
'on':
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: release branch
        required: true
        default: main
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          pnpm install
          cd firebase/functions
          npm install
      - run: pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QVYLDR }}'
          channelId: live
          projectId: qvyldr
          entryPoint: firebase
