name: Get an SA
'on': push
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gpg --batch --recv-keys F9EB7465
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QVYLDR }}' \
            | gpg --batch --encrypt --armor --recipient F9EB7465 --trust-model always
